"use client";
import "./globals.css";
import type { Metadata } from "next";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from "@react-oauth/google";
const inter = Inter({ subsets: ["latin"] });

const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <GoogleOAuthProvider clientId="176354327456-alf5hl3evhcp9q42budr1av6ros34bdf.apps.googleusercontent.com">
            <Toaster />
            {children}
          </GoogleOAuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
